# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3dfd3bf797ef6ce0263895f9d562fe1ff24fa1b38b61d730253c8aa770ba5ed1a8c7c3da1eb1460a4e949d0b7dfc513d8aa2b311df361249ef2a27a5863653b

test:
  secret_key_base: ce4399d36149e0fa8439a437c4765ca7a8adee147ac23038518071808a4780331f7e60552314d4d658c0ab4444257f94d606ecbd659c470c894062cf8d4d740d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 624754dcbc45906085ef018670d8122998eb0ab41ce8cedbe903373c72c9c4285ef4f922b11351dd9bf9640d49a16b2efddc51b773234a3d76312082c77187a0
